### ISSUE TITLE
[Forum] Simplify post permissions

### ISSUE THREAD

**Issue by meredevelopment** [keith-b-git/ct#10]
### Is your feature request related to a problem? 
It's based on user feedback ([Here](https://club.triumph.org.uk/menu/1/item/599203/view?messagepage=10)), and fairly frequent occurrence of miss-tagged posts.

### Additional context
Simplification of 'Viewable by' and 'Replyable by' options. Currently the options are these:

**Non-members:**

<img width="415" alt="image" src="https://user-images.githubusercontent.com/3437528/62839122-9946d200-bc7d-11e9-88d1-c41b2e0413d0.png">

**Members (Standard):**
I don't have access to a non-moderator, member account. Please expand on what a standard member sees Keith if you can.

**Members (Moderator):**
<img width="889" alt="image" src="https://user-images.githubusercontent.com/3437528/62839171-2722bd00-bc7e-11e9-9c0d-b2ab9ab6cf7f.png">

The suggestion is that these options are reduced as much as possible to avoid confusion. Here are some exploratory questions: 

- What is the benefit of having the 'Website Guest User' AND the 'All' option? 
- The granular Viewable and Replyable by options are no-doubt useful for other website content, but for Forum posts, might they be combined/implied? I.e if a post is viewable by 'Club Members' it should also be repayable by them.
- Is viewable by 'Draft' being used or likely to be used by forum posters?
- Is repayable by 'self' a good idea for regular forum users? I wonder if it allows 'fire-and-forget' type posts. Seems like a privilege-only option to me. 

### Describe the solution you'd like
Please let me know what you think. I think my ideal personal scenario might be: 

**Non-members:**
No options. A post is just a post.

**Members (Standard):**
Two options, viewable & replyable by 'Club Members' or 'Everyone'.

**Comment by keith-b-git** [comment]
A lot of this is addressed in the 'new' version which is soon to be rolled out.
The form is presented in both a 'simple' and 'advanced' form, the former not having any options.
The permissions in 'advanced' are simpler, removing the separate options for 'reply', a member will see 'club members' , 'registered users' & 'all', non member just the latter two.
![image](https://user-images.githubusercontent.com/13632634/62839940-517a7780-bc8a-11e9-92e0-c910651aea9b.png)
I believe there may be value in being able to restrict content to registered users rather than the internet at large, but agree it will not be widely used.
Let me know if you want to have play with it and I'll open a port up.

**Comment by meredevelopment** [comment]
Looks and sounds perfect! I'll mail you separately for some access. I'll leave this issue open for now if that's ok with you, but have marked it as 'on hold' while the new version is finished.

**Comment by meredevelopment** [comment]
Thanks @keith-b-git, Now live, looking good and working well 👍🏻
