### ISSUE TITLE
[Forum] Top Ten view shows 8 results.

### ISSUE THREAD

**Issue by meredevelopment** [keith-b-git/ct#2]
### Expected Behaviour

Viewing the 'Top Ten' to show 10 results.

### Actual Behaviour

https://club.triumph.org.uk/menu/1/top_ten Currently shows 8.

**Comment by keith-b-git** [comment]
OK, the way this works was actually a bit of bodge because I couldn't find an easy way of doing it with a single database query. What it is actually doing is pulling the latest 50 threads from the DB and then searching them for the top ten unread ones. Hence if you've read more than 40 of them it won't find ten. I need to have a rethink on this!

**Comment by meredevelopment** [comment]
Sounds to me this is related to #11 and another issue related to ‘read status’ that I’m about to open. So putting this on hold for now as it might end up surplus to requirements.

**Comment by meredevelopment** [comment]
No longer relevant, as #15 replaces this functionality.
