### ISSUE TITLE
[Forum] Remove 'Stickies' from 'View all threads' view.

### ISSUE THREAD

**Issue by meredevelopment** [keith-b-git/ct#4]
The 'View all threads' view (The https://club.triumph.org.uk/menu/1/threads) shows stickies. I believe this limits the usability of the view because stickies are taken out of context and get in the way of the chronological view I believe users want.

I would prefer to see a full chronological 'newest-first' view, similar to Top Ten. 

The button description "View all threads (# threads)" might be changed to "View all posts in date order" or just "View all posts".

**Comment by keith-b-git** [comment]
The problem here is that the query that generates the list on the front page is the same one that does it on the subpages and things just cascade down. I think the ideal behaviour would be for the 'stickyness' not to cascade down and only appear on the subpage.
One option might be to have a checkbox to select two different views, but that seems a bit messy.
I've found a compromise which is to only put stickies at the top of pages where posting is allowed, i.e. not to display it on pages where you can only view posts but not create them like the home page or the 'cars' top page.
I think that gives reasonably intuitive solution.
I've renamed the button.

**Comment by meredevelopment** [comment]
That’s a perfect solution I think. Good job. I’m going to close this, but if you feel it needs more tweaking please reopen it.

**Comment by meredevelopment** [comment]
Colin noticed almost straight away: 

“Just noticed that all the Sticky threads have disappeared from the search.

will make it a lot easier to see what has been posted if there has been more that half a dozen new ones” 👍👍👍
